//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolarionPlug.ProjectApi {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.polarion.com/ProjectWebService", ConfigurationName="ProjectApi.ProjectWebService")]
    internal interface ProjectWebService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message createUserRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PolarionPlug.ProjectApi.createUserResponse createUser(PolarionPlug.ProjectApi.createUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.createUserResponse> createUserAsync(PolarionPlug.ProjectApi.createUserRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getContainedGroupsRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PolarionPlug.ProjectApi.getContainedGroupsResponse getContainedGroups(PolarionPlug.ProjectApi.getContainedGroupsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getContainedGroupsResponse> getContainedGroupsAsync(PolarionPlug.ProjectApi.getContainedGroupsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getContainedProjectsRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PolarionPlug.ProjectApi.getContainedProjectsResponse getContainedProjects(PolarionPlug.ProjectApi.getContainedProjectsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getContainedProjectsResponse> getContainedProjectsAsync(PolarionPlug.ProjectApi.getContainedProjectsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getDeepContainedProjectsRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PolarionPlug.ProjectApi.getDeepContainedProjectsResponse getDeepContainedProjects(PolarionPlug.ProjectApi.getDeepContainedProjectsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getDeepContainedProjectsResponse> getDeepContainedProjectsAsync(PolarionPlug.ProjectApi.getDeepContainedProjectsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getProjectRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PolarionPlug.ProjectApi.getProjectResponse getProject(PolarionPlug.ProjectApi.getProjectRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getProjectResponse> getProjectAsync(PolarionPlug.ProjectApi.getProjectRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getProjectAtLocationRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PolarionPlug.ProjectApi.getProjectAtLocationResponse getProjectAtLocation(PolarionPlug.ProjectApi.getProjectAtLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getProjectAtLocationResponse> getProjectAtLocationAsync(PolarionPlug.ProjectApi.getProjectAtLocationRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getProjectByURIRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PolarionPlug.ProjectApi.getProjectByURIResponse getProjectByURI(PolarionPlug.ProjectApi.getProjectByURIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getProjectByURIResponse> getProjectByURIAsync(PolarionPlug.ProjectApi.getProjectByURIRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getProjectGroupRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PolarionPlug.ProjectApi.getProjectGroupResponse getProjectGroup(PolarionPlug.ProjectApi.getProjectGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getProjectGroupResponse> getProjectGroupAsync(PolarionPlug.ProjectApi.getProjectGroupRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getProjectGroupAtLocationRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PolarionPlug.ProjectApi.getProjectGroupAtLocationResponse getProjectGroupAtLocation(PolarionPlug.ProjectApi.getProjectGroupAtLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getProjectGroupAtLocationResponse> getProjectGroupAtLocationAsync(PolarionPlug.ProjectApi.getProjectGroupAtLocationRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getProjectUsersRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PolarionPlug.ProjectApi.getProjectUsersResponse getProjectUsers(PolarionPlug.ProjectApi.getProjectUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getProjectUsersResponse> getProjectUsersAsync(PolarionPlug.ProjectApi.getProjectUsersRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getRootProjectGroupRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PolarionPlug.ProjectApi.getRootProjectGroupResponse getRootProjectGroup(PolarionPlug.ProjectApi.getRootProjectGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getRootProjectGroupResponse> getRootProjectGroupAsync(PolarionPlug.ProjectApi.getRootProjectGroupRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getUserRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PolarionPlug.ProjectApi.getUserResponse getUser(PolarionPlug.ProjectApi.getUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getUserResponse> getUserAsync(PolarionPlug.ProjectApi.getUserRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getUserAvatarURLRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PolarionPlug.ProjectApi.getUserAvatarURLResponse getUserAvatarURL(PolarionPlug.ProjectApi.getUserAvatarURLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getUserAvatarURLResponse> getUserAvatarURLAsync(PolarionPlug.ProjectApi.getUserAvatarURLRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getUserByUriRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PolarionPlug.ProjectApi.getUserByUriResponse getUserByUri(PolarionPlug.ProjectApi.getUserByUriRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getUserByUriResponse> getUserByUriAsync(PolarionPlug.ProjectApi.getUserByUriRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message getUsersRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PolarionPlug.ProjectApi.getUsersResponse getUsers(PolarionPlug.ProjectApi.getUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getUsersResponse> getUsersAsync(PolarionPlug.ProjectApi.getUsersRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://ws.polarion.com/ProjectWebService-impl) of message updateUserRequest does not match the default value (http://ws.polarion.com/ProjectWebService)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PolarionPlug.ProjectApi.updateUserResponse updateUser(PolarionPlug.ProjectApi.updateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.updateUserResponse> updateUserAsync(PolarionPlug.ProjectApi.updateUserRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.polarion.com/ProjectWebService-types")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Text descriptionField;
        
        private bool disabledNotificationsField;
        
        private bool disabledNotificationsFieldSpecified;
        
        private string emailField;
        
        private Text homePageContentField;
        
        private string idField;
        
        private string nameField;
        
        private string[] voteURIsField;
        
        private string[] watcheURIsField;
        
        private string uriField;
        
        private bool unresolvableField;
        
        private bool unresolvableFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Text description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool disabledNotifications {
            get {
                return this.disabledNotificationsField;
            }
            set {
                this.disabledNotificationsField = value;
                this.RaisePropertyChanged("disabledNotifications");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool disabledNotificationsSpecified {
            get {
                return this.disabledNotificationsFieldSpecified;
            }
            set {
                this.disabledNotificationsFieldSpecified = value;
                this.RaisePropertyChanged("disabledNotificationsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Text homePageContent {
            get {
                return this.homePageContentField;
            }
            set {
                this.homePageContentField = value;
                this.RaisePropertyChanged("homePageContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SubterraURI", Namespace="http://ws.polarion.com/types", IsNullable=false)]
        public string[] voteURIs {
            get {
                return this.voteURIsField;
            }
            set {
                this.voteURIsField = value;
                this.RaisePropertyChanged("voteURIs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SubterraURI", Namespace="http://ws.polarion.com/types", IsNullable=false)]
        public string[] watcheURIs {
            get {
                return this.watcheURIsField;
            }
            set {
                this.watcheURIsField = value;
                this.RaisePropertyChanged("watcheURIs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
                this.RaisePropertyChanged("uri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool unresolvable {
            get {
                return this.unresolvableField;
            }
            set {
                this.unresolvableField = value;
                this.RaisePropertyChanged("unresolvable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unresolvableSpecified {
            get {
                return this.unresolvableFieldSpecified;
            }
            set {
                this.unresolvableFieldSpecified = value;
                this.RaisePropertyChanged("unresolvableSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.polarion.com/types")]
    public partial class Text : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string contentField;
        
        private bool contentLossyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool contentLossy {
            get {
                return this.contentLossyField;
            }
            set {
                this.contentLossyField = value;
                this.RaisePropertyChanged("contentLossy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.polarion.com/ProjectWebService-types")]
    public partial class Project : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activeField;
        
        private bool activeFieldSpecified;
        
        private Text descriptionField;
        
        private System.DateTime finishField;
        
        private bool finishFieldSpecified;
        
        private string idField;
        
        private User leadField;
        
        private string locationField;
        
        private System.DateTime lockWorkRecordsDateField;
        
        private bool lockWorkRecordsDateFieldSpecified;
        
        private string nameField;
        
        private string projectGroupURIField;
        
        private System.DateTime startField;
        
        private bool startFieldSpecified;
        
        private string trackerPrefixField;
        
        private string uriField;
        
        private bool unresolvableField;
        
        private bool unresolvableFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeSpecified {
            get {
                return this.activeFieldSpecified;
            }
            set {
                this.activeFieldSpecified = value;
                this.RaisePropertyChanged("activeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Text description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime finish {
            get {
                return this.finishField;
            }
            set {
                this.finishField = value;
                this.RaisePropertyChanged("finish");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool finishSpecified {
            get {
                return this.finishFieldSpecified;
            }
            set {
                this.finishFieldSpecified = value;
                this.RaisePropertyChanged("finishSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public User lead {
            get {
                return this.leadField;
            }
            set {
                this.leadField = value;
                this.RaisePropertyChanged("lead");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime lockWorkRecordsDate {
            get {
                return this.lockWorkRecordsDateField;
            }
            set {
                this.lockWorkRecordsDateField = value;
                this.RaisePropertyChanged("lockWorkRecordsDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lockWorkRecordsDateSpecified {
            get {
                return this.lockWorkRecordsDateFieldSpecified;
            }
            set {
                this.lockWorkRecordsDateFieldSpecified = value;
                this.RaisePropertyChanged("lockWorkRecordsDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string projectGroupURI {
            get {
                return this.projectGroupURIField;
            }
            set {
                this.projectGroupURIField = value;
                this.RaisePropertyChanged("projectGroupURI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=9)]
        public System.DateTime start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startSpecified {
            get {
                return this.startFieldSpecified;
            }
            set {
                this.startFieldSpecified = value;
                this.RaisePropertyChanged("startSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string trackerPrefix {
            get {
                return this.trackerPrefixField;
            }
            set {
                this.trackerPrefixField = value;
                this.RaisePropertyChanged("trackerPrefix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
                this.RaisePropertyChanged("uri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool unresolvable {
            get {
                return this.unresolvableField;
            }
            set {
                this.unresolvableField = value;
                this.RaisePropertyChanged("unresolvable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unresolvableSpecified {
            get {
                return this.unresolvableFieldSpecified;
            }
            set {
                this.unresolvableFieldSpecified = value;
                this.RaisePropertyChanged("unresolvableSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.polarion.com/ProjectWebService-types")]
    public partial class ProjectGroup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] groupURIsField;
        
        private string locationField;
        
        private string nameField;
        
        private string parentURIField;
        
        private string[] projectIDsField;
        
        private string uriField;
        
        private bool unresolvableField;
        
        private bool unresolvableFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SubterraURI", Namespace="http://ws.polarion.com/types", IsNullable=false)]
        public string[] groupURIs {
            get {
                return this.groupURIsField;
            }
            set {
                this.groupURIsField = value;
                this.RaisePropertyChanged("groupURIs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string parentURI {
            get {
                return this.parentURIField;
            }
            set {
                this.parentURIField = value;
                this.RaisePropertyChanged("parentURI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://ws.polarion.com/types", IsNullable=false)]
        public string[] projectIDs {
            get {
                return this.projectIDsField;
            }
            set {
                this.projectIDsField = value;
                this.RaisePropertyChanged("projectIDs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
                this.RaisePropertyChanged("uri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool unresolvable {
            get {
                return this.unresolvableField;
            }
            set {
                this.unresolvableField = value;
                this.RaisePropertyChanged("unresolvable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool unresolvableSpecified {
            get {
                return this.unresolvableFieldSpecified;
            }
            set {
                this.unresolvableFieldSpecified = value;
                this.RaisePropertyChanged("unresolvableSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUser", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class createUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string in0;
        
        public createUserRequest() {
        }
        
        public createUserRequest(string in0) {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createUserResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class createUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public PolarionPlug.ProjectApi.User createUserReturn;
        
        public createUserResponse() {
        }
        
        public createUserResponse(PolarionPlug.ProjectApi.User createUserReturn) {
            this.createUserReturn = createUserReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getContainedGroups", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getContainedGroupsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string projectGroupURI;
        
        public getContainedGroupsRequest() {
        }
        
        public getContainedGroupsRequest(string projectGroupURI) {
            this.projectGroupURI = projectGroupURI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getContainedGroupsResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getContainedGroupsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getContainedGroupsReturn")]
        public PolarionPlug.ProjectApi.ProjectGroup[] getContainedGroupsReturn;
        
        public getContainedGroupsResponse() {
        }
        
        public getContainedGroupsResponse(PolarionPlug.ProjectApi.ProjectGroup[] getContainedGroupsReturn) {
            this.getContainedGroupsReturn = getContainedGroupsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getContainedProjects", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getContainedProjectsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string projectGroupURI;
        
        public getContainedProjectsRequest() {
        }
        
        public getContainedProjectsRequest(string projectGroupURI) {
            this.projectGroupURI = projectGroupURI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getContainedProjectsResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getContainedProjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getContainedProjectsReturn")]
        public PolarionPlug.ProjectApi.Project[] getContainedProjectsReturn;
        
        public getContainedProjectsResponse() {
        }
        
        public getContainedProjectsResponse(PolarionPlug.ProjectApi.Project[] getContainedProjectsReturn) {
            this.getContainedProjectsReturn = getContainedProjectsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDeepContainedProjects", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getDeepContainedProjectsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string projectGroupURI;
        
        public getDeepContainedProjectsRequest() {
        }
        
        public getDeepContainedProjectsRequest(string projectGroupURI) {
            this.projectGroupURI = projectGroupURI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDeepContainedProjectsResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getDeepContainedProjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getDeepContainedProjectsReturn")]
        public PolarionPlug.ProjectApi.Project[] getDeepContainedProjectsReturn;
        
        public getDeepContainedProjectsResponse() {
        }
        
        public getDeepContainedProjectsResponse(PolarionPlug.ProjectApi.Project[] getDeepContainedProjectsReturn) {
            this.getDeepContainedProjectsReturn = getDeepContainedProjectsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProject", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getProjectRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string projectID;
        
        public getProjectRequest() {
        }
        
        public getProjectRequest(string projectID) {
            this.projectID = projectID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getProjectResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public PolarionPlug.ProjectApi.Project getProjectReturn;
        
        public getProjectResponse() {
        }
        
        public getProjectResponse(PolarionPlug.ProjectApi.Project getProjectReturn) {
            this.getProjectReturn = getProjectReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectAtLocation", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getProjectAtLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string location;
        
        public getProjectAtLocationRequest() {
        }
        
        public getProjectAtLocationRequest(string location) {
            this.location = location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectAtLocationResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getProjectAtLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public PolarionPlug.ProjectApi.Project getProjectAtLocationReturn;
        
        public getProjectAtLocationResponse() {
        }
        
        public getProjectAtLocationResponse(PolarionPlug.ProjectApi.Project getProjectAtLocationReturn) {
            this.getProjectAtLocationReturn = getProjectAtLocationReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectByURI", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getProjectByURIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string projectURI;
        
        public getProjectByURIRequest() {
        }
        
        public getProjectByURIRequest(string projectURI) {
            this.projectURI = projectURI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectByURIResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getProjectByURIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public PolarionPlug.ProjectApi.Project getProjectByURIReturn;
        
        public getProjectByURIResponse() {
        }
        
        public getProjectByURIResponse(PolarionPlug.ProjectApi.Project getProjectByURIReturn) {
            this.getProjectByURIReturn = getProjectByURIReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectGroup", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getProjectGroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string projectGroupURI;
        
        public getProjectGroupRequest() {
        }
        
        public getProjectGroupRequest(string projectGroupURI) {
            this.projectGroupURI = projectGroupURI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectGroupResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getProjectGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public PolarionPlug.ProjectApi.ProjectGroup getProjectGroupReturn;
        
        public getProjectGroupResponse() {
        }
        
        public getProjectGroupResponse(PolarionPlug.ProjectApi.ProjectGroup getProjectGroupReturn) {
            this.getProjectGroupReturn = getProjectGroupReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectGroupAtLocation", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getProjectGroupAtLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string location;
        
        public getProjectGroupAtLocationRequest() {
        }
        
        public getProjectGroupAtLocationRequest(string location) {
            this.location = location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectGroupAtLocationResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getProjectGroupAtLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public PolarionPlug.ProjectApi.ProjectGroup getProjectGroupAtLocationReturn;
        
        public getProjectGroupAtLocationResponse() {
        }
        
        public getProjectGroupAtLocationResponse(PolarionPlug.ProjectApi.ProjectGroup getProjectGroupAtLocationReturn) {
            this.getProjectGroupAtLocationReturn = getProjectGroupAtLocationReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectUsers", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getProjectUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string projectID;
        
        public getProjectUsersRequest() {
        }
        
        public getProjectUsersRequest(string projectID) {
            this.projectID = projectID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProjectUsersResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getProjectUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getProjectUsersReturn")]
        public PolarionPlug.ProjectApi.User[] getProjectUsersReturn;
        
        public getProjectUsersResponse() {
        }
        
        public getProjectUsersResponse(PolarionPlug.ProjectApi.User[] getProjectUsersReturn) {
            this.getProjectUsersReturn = getProjectUsersReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRootProjectGroup", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getRootProjectGroupRequest {
        
        public getRootProjectGroupRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRootProjectGroupResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getRootProjectGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public PolarionPlug.ProjectApi.ProjectGroup getRootProjectGroupReturn;
        
        public getRootProjectGroupResponse() {
        }
        
        public getRootProjectGroupResponse(PolarionPlug.ProjectApi.ProjectGroup getRootProjectGroupReturn) {
            this.getRootProjectGroupReturn = getRootProjectGroupReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUser", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string userID;
        
        public getUserRequest() {
        }
        
        public getUserRequest(string userID) {
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public PolarionPlug.ProjectApi.User getUserReturn;
        
        public getUserResponse() {
        }
        
        public getUserResponse(PolarionPlug.ProjectApi.User getUserReturn) {
            this.getUserReturn = getUserReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserAvatarURL", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getUserAvatarURLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string userURI;
        
        public getUserAvatarURLRequest() {
        }
        
        public getUserAvatarURLRequest(string userURI) {
            this.userURI = userURI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserAvatarURLResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getUserAvatarURLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string getUserAvatarURLReturn;
        
        public getUserAvatarURLResponse() {
        }
        
        public getUserAvatarURLResponse(string getUserAvatarURLReturn) {
            this.getUserAvatarURLReturn = getUserAvatarURLReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserByUri", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getUserByUriRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public string userURI;
        
        public getUserByUriRequest() {
        }
        
        public getUserByUriRequest(string userURI) {
            this.userURI = userURI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserByUriResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getUserByUriResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public PolarionPlug.ProjectApi.User getUserByUriReturn;
        
        public getUserByUriResponse() {
        }
        
        public getUserByUriResponse(PolarionPlug.ProjectApi.User getUserByUriReturn) {
            this.getUserByUriReturn = getUserByUriReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsers", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getUsersRequest {
        
        public getUsersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsersResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class getUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("getUsersReturn")]
        public PolarionPlug.ProjectApi.User[] getUsersReturn;
        
        public getUsersResponse() {
        }
        
        public getUsersResponse(PolarionPlug.ProjectApi.User[] getUsersReturn) {
            this.getUsersReturn = getUsersReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateUser", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class updateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.polarion.com/ProjectWebService-impl", Order=0)]
        public PolarionPlug.ProjectApi.User in0;
        
        public updateUserRequest() {
        }
        
        public updateUserRequest(PolarionPlug.ProjectApi.User in0) {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateUserResponse", WrapperNamespace="http://ws.polarion.com/ProjectWebService-impl", IsWrapped=true)]
    internal partial class updateUserResponse {
        
        public updateUserResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ProjectWebServiceChannel : PolarionPlug.ProjectApi.ProjectWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ProjectWebServiceClient : System.ServiceModel.ClientBase<PolarionPlug.ProjectApi.ProjectWebService>, PolarionPlug.ProjectApi.ProjectWebService {
        
        public ProjectWebServiceClient() {
        }
        
        public ProjectWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolarionPlug.ProjectApi.createUserResponse PolarionPlug.ProjectApi.ProjectWebService.createUser(PolarionPlug.ProjectApi.createUserRequest request) {
            return base.Channel.createUser(request);
        }
        
        public PolarionPlug.ProjectApi.User createUser(string in0) {
            PolarionPlug.ProjectApi.createUserRequest inValue = new PolarionPlug.ProjectApi.createUserRequest();
            inValue.in0 = in0;
            PolarionPlug.ProjectApi.createUserResponse retVal = ((PolarionPlug.ProjectApi.ProjectWebService)(this)).createUser(inValue);
            return retVal.createUserReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.createUserResponse> PolarionPlug.ProjectApi.ProjectWebService.createUserAsync(PolarionPlug.ProjectApi.createUserRequest request) {
            return base.Channel.createUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionPlug.ProjectApi.createUserResponse> createUserAsync(string in0) {
            PolarionPlug.ProjectApi.createUserRequest inValue = new PolarionPlug.ProjectApi.createUserRequest();
            inValue.in0 = in0;
            return ((PolarionPlug.ProjectApi.ProjectWebService)(this)).createUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolarionPlug.ProjectApi.getContainedGroupsResponse PolarionPlug.ProjectApi.ProjectWebService.getContainedGroups(PolarionPlug.ProjectApi.getContainedGroupsRequest request) {
            return base.Channel.getContainedGroups(request);
        }
        
        public PolarionPlug.ProjectApi.ProjectGroup[] getContainedGroups(string projectGroupURI) {
            PolarionPlug.ProjectApi.getContainedGroupsRequest inValue = new PolarionPlug.ProjectApi.getContainedGroupsRequest();
            inValue.projectGroupURI = projectGroupURI;
            PolarionPlug.ProjectApi.getContainedGroupsResponse retVal = ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getContainedGroups(inValue);
            return retVal.getContainedGroupsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getContainedGroupsResponse> PolarionPlug.ProjectApi.ProjectWebService.getContainedGroupsAsync(PolarionPlug.ProjectApi.getContainedGroupsRequest request) {
            return base.Channel.getContainedGroupsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getContainedGroupsResponse> getContainedGroupsAsync(string projectGroupURI) {
            PolarionPlug.ProjectApi.getContainedGroupsRequest inValue = new PolarionPlug.ProjectApi.getContainedGroupsRequest();
            inValue.projectGroupURI = projectGroupURI;
            return ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getContainedGroupsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolarionPlug.ProjectApi.getContainedProjectsResponse PolarionPlug.ProjectApi.ProjectWebService.getContainedProjects(PolarionPlug.ProjectApi.getContainedProjectsRequest request) {
            return base.Channel.getContainedProjects(request);
        }
        
        public PolarionPlug.ProjectApi.Project[] getContainedProjects(string projectGroupURI) {
            PolarionPlug.ProjectApi.getContainedProjectsRequest inValue = new PolarionPlug.ProjectApi.getContainedProjectsRequest();
            inValue.projectGroupURI = projectGroupURI;
            PolarionPlug.ProjectApi.getContainedProjectsResponse retVal = ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getContainedProjects(inValue);
            return retVal.getContainedProjectsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getContainedProjectsResponse> PolarionPlug.ProjectApi.ProjectWebService.getContainedProjectsAsync(PolarionPlug.ProjectApi.getContainedProjectsRequest request) {
            return base.Channel.getContainedProjectsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getContainedProjectsResponse> getContainedProjectsAsync(string projectGroupURI) {
            PolarionPlug.ProjectApi.getContainedProjectsRequest inValue = new PolarionPlug.ProjectApi.getContainedProjectsRequest();
            inValue.projectGroupURI = projectGroupURI;
            return ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getContainedProjectsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolarionPlug.ProjectApi.getDeepContainedProjectsResponse PolarionPlug.ProjectApi.ProjectWebService.getDeepContainedProjects(PolarionPlug.ProjectApi.getDeepContainedProjectsRequest request) {
            return base.Channel.getDeepContainedProjects(request);
        }
        
        public PolarionPlug.ProjectApi.Project[] getDeepContainedProjects(string projectGroupURI) {
            PolarionPlug.ProjectApi.getDeepContainedProjectsRequest inValue = new PolarionPlug.ProjectApi.getDeepContainedProjectsRequest();
            inValue.projectGroupURI = projectGroupURI;
            PolarionPlug.ProjectApi.getDeepContainedProjectsResponse retVal = ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getDeepContainedProjects(inValue);
            return retVal.getDeepContainedProjectsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getDeepContainedProjectsResponse> PolarionPlug.ProjectApi.ProjectWebService.getDeepContainedProjectsAsync(PolarionPlug.ProjectApi.getDeepContainedProjectsRequest request) {
            return base.Channel.getDeepContainedProjectsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getDeepContainedProjectsResponse> getDeepContainedProjectsAsync(string projectGroupURI) {
            PolarionPlug.ProjectApi.getDeepContainedProjectsRequest inValue = new PolarionPlug.ProjectApi.getDeepContainedProjectsRequest();
            inValue.projectGroupURI = projectGroupURI;
            return ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getDeepContainedProjectsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolarionPlug.ProjectApi.getProjectResponse PolarionPlug.ProjectApi.ProjectWebService.getProject(PolarionPlug.ProjectApi.getProjectRequest request) {
            return base.Channel.getProject(request);
        }
        
        public PolarionPlug.ProjectApi.Project getProject(string projectID) {
            PolarionPlug.ProjectApi.getProjectRequest inValue = new PolarionPlug.ProjectApi.getProjectRequest();
            inValue.projectID = projectID;
            PolarionPlug.ProjectApi.getProjectResponse retVal = ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getProject(inValue);
            return retVal.getProjectReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getProjectResponse> PolarionPlug.ProjectApi.ProjectWebService.getProjectAsync(PolarionPlug.ProjectApi.getProjectRequest request) {
            return base.Channel.getProjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getProjectResponse> getProjectAsync(string projectID) {
            PolarionPlug.ProjectApi.getProjectRequest inValue = new PolarionPlug.ProjectApi.getProjectRequest();
            inValue.projectID = projectID;
            return ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getProjectAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolarionPlug.ProjectApi.getProjectAtLocationResponse PolarionPlug.ProjectApi.ProjectWebService.getProjectAtLocation(PolarionPlug.ProjectApi.getProjectAtLocationRequest request) {
            return base.Channel.getProjectAtLocation(request);
        }
        
        public PolarionPlug.ProjectApi.Project getProjectAtLocation(string location) {
            PolarionPlug.ProjectApi.getProjectAtLocationRequest inValue = new PolarionPlug.ProjectApi.getProjectAtLocationRequest();
            inValue.location = location;
            PolarionPlug.ProjectApi.getProjectAtLocationResponse retVal = ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getProjectAtLocation(inValue);
            return retVal.getProjectAtLocationReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getProjectAtLocationResponse> PolarionPlug.ProjectApi.ProjectWebService.getProjectAtLocationAsync(PolarionPlug.ProjectApi.getProjectAtLocationRequest request) {
            return base.Channel.getProjectAtLocationAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getProjectAtLocationResponse> getProjectAtLocationAsync(string location) {
            PolarionPlug.ProjectApi.getProjectAtLocationRequest inValue = new PolarionPlug.ProjectApi.getProjectAtLocationRequest();
            inValue.location = location;
            return ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getProjectAtLocationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolarionPlug.ProjectApi.getProjectByURIResponse PolarionPlug.ProjectApi.ProjectWebService.getProjectByURI(PolarionPlug.ProjectApi.getProjectByURIRequest request) {
            return base.Channel.getProjectByURI(request);
        }
        
        public PolarionPlug.ProjectApi.Project getProjectByURI(string projectURI) {
            PolarionPlug.ProjectApi.getProjectByURIRequest inValue = new PolarionPlug.ProjectApi.getProjectByURIRequest();
            inValue.projectURI = projectURI;
            PolarionPlug.ProjectApi.getProjectByURIResponse retVal = ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getProjectByURI(inValue);
            return retVal.getProjectByURIReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getProjectByURIResponse> PolarionPlug.ProjectApi.ProjectWebService.getProjectByURIAsync(PolarionPlug.ProjectApi.getProjectByURIRequest request) {
            return base.Channel.getProjectByURIAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getProjectByURIResponse> getProjectByURIAsync(string projectURI) {
            PolarionPlug.ProjectApi.getProjectByURIRequest inValue = new PolarionPlug.ProjectApi.getProjectByURIRequest();
            inValue.projectURI = projectURI;
            return ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getProjectByURIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolarionPlug.ProjectApi.getProjectGroupResponse PolarionPlug.ProjectApi.ProjectWebService.getProjectGroup(PolarionPlug.ProjectApi.getProjectGroupRequest request) {
            return base.Channel.getProjectGroup(request);
        }
        
        public PolarionPlug.ProjectApi.ProjectGroup getProjectGroup(string projectGroupURI) {
            PolarionPlug.ProjectApi.getProjectGroupRequest inValue = new PolarionPlug.ProjectApi.getProjectGroupRequest();
            inValue.projectGroupURI = projectGroupURI;
            PolarionPlug.ProjectApi.getProjectGroupResponse retVal = ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getProjectGroup(inValue);
            return retVal.getProjectGroupReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getProjectGroupResponse> PolarionPlug.ProjectApi.ProjectWebService.getProjectGroupAsync(PolarionPlug.ProjectApi.getProjectGroupRequest request) {
            return base.Channel.getProjectGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getProjectGroupResponse> getProjectGroupAsync(string projectGroupURI) {
            PolarionPlug.ProjectApi.getProjectGroupRequest inValue = new PolarionPlug.ProjectApi.getProjectGroupRequest();
            inValue.projectGroupURI = projectGroupURI;
            return ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getProjectGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolarionPlug.ProjectApi.getProjectGroupAtLocationResponse PolarionPlug.ProjectApi.ProjectWebService.getProjectGroupAtLocation(PolarionPlug.ProjectApi.getProjectGroupAtLocationRequest request) {
            return base.Channel.getProjectGroupAtLocation(request);
        }
        
        public PolarionPlug.ProjectApi.ProjectGroup getProjectGroupAtLocation(string location) {
            PolarionPlug.ProjectApi.getProjectGroupAtLocationRequest inValue = new PolarionPlug.ProjectApi.getProjectGroupAtLocationRequest();
            inValue.location = location;
            PolarionPlug.ProjectApi.getProjectGroupAtLocationResponse retVal = ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getProjectGroupAtLocation(inValue);
            return retVal.getProjectGroupAtLocationReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getProjectGroupAtLocationResponse> PolarionPlug.ProjectApi.ProjectWebService.getProjectGroupAtLocationAsync(PolarionPlug.ProjectApi.getProjectGroupAtLocationRequest request) {
            return base.Channel.getProjectGroupAtLocationAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getProjectGroupAtLocationResponse> getProjectGroupAtLocationAsync(string location) {
            PolarionPlug.ProjectApi.getProjectGroupAtLocationRequest inValue = new PolarionPlug.ProjectApi.getProjectGroupAtLocationRequest();
            inValue.location = location;
            return ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getProjectGroupAtLocationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolarionPlug.ProjectApi.getProjectUsersResponse PolarionPlug.ProjectApi.ProjectWebService.getProjectUsers(PolarionPlug.ProjectApi.getProjectUsersRequest request) {
            return base.Channel.getProjectUsers(request);
        }
        
        public PolarionPlug.ProjectApi.User[] getProjectUsers(string projectID) {
            PolarionPlug.ProjectApi.getProjectUsersRequest inValue = new PolarionPlug.ProjectApi.getProjectUsersRequest();
            inValue.projectID = projectID;
            PolarionPlug.ProjectApi.getProjectUsersResponse retVal = ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getProjectUsers(inValue);
            return retVal.getProjectUsersReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getProjectUsersResponse> PolarionPlug.ProjectApi.ProjectWebService.getProjectUsersAsync(PolarionPlug.ProjectApi.getProjectUsersRequest request) {
            return base.Channel.getProjectUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getProjectUsersResponse> getProjectUsersAsync(string projectID) {
            PolarionPlug.ProjectApi.getProjectUsersRequest inValue = new PolarionPlug.ProjectApi.getProjectUsersRequest();
            inValue.projectID = projectID;
            return ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getProjectUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolarionPlug.ProjectApi.getRootProjectGroupResponse PolarionPlug.ProjectApi.ProjectWebService.getRootProjectGroup(PolarionPlug.ProjectApi.getRootProjectGroupRequest request) {
            return base.Channel.getRootProjectGroup(request);
        }
        
        public PolarionPlug.ProjectApi.ProjectGroup getRootProjectGroup() {
            PolarionPlug.ProjectApi.getRootProjectGroupRequest inValue = new PolarionPlug.ProjectApi.getRootProjectGroupRequest();
            PolarionPlug.ProjectApi.getRootProjectGroupResponse retVal = ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getRootProjectGroup(inValue);
            return retVal.getRootProjectGroupReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getRootProjectGroupResponse> PolarionPlug.ProjectApi.ProjectWebService.getRootProjectGroupAsync(PolarionPlug.ProjectApi.getRootProjectGroupRequest request) {
            return base.Channel.getRootProjectGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getRootProjectGroupResponse> getRootProjectGroupAsync() {
            PolarionPlug.ProjectApi.getRootProjectGroupRequest inValue = new PolarionPlug.ProjectApi.getRootProjectGroupRequest();
            return ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getRootProjectGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolarionPlug.ProjectApi.getUserResponse PolarionPlug.ProjectApi.ProjectWebService.getUser(PolarionPlug.ProjectApi.getUserRequest request) {
            return base.Channel.getUser(request);
        }
        
        public PolarionPlug.ProjectApi.User getUser(string userID) {
            PolarionPlug.ProjectApi.getUserRequest inValue = new PolarionPlug.ProjectApi.getUserRequest();
            inValue.userID = userID;
            PolarionPlug.ProjectApi.getUserResponse retVal = ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getUser(inValue);
            return retVal.getUserReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getUserResponse> PolarionPlug.ProjectApi.ProjectWebService.getUserAsync(PolarionPlug.ProjectApi.getUserRequest request) {
            return base.Channel.getUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getUserResponse> getUserAsync(string userID) {
            PolarionPlug.ProjectApi.getUserRequest inValue = new PolarionPlug.ProjectApi.getUserRequest();
            inValue.userID = userID;
            return ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolarionPlug.ProjectApi.getUserAvatarURLResponse PolarionPlug.ProjectApi.ProjectWebService.getUserAvatarURL(PolarionPlug.ProjectApi.getUserAvatarURLRequest request) {
            return base.Channel.getUserAvatarURL(request);
        }
        
        public string getUserAvatarURL(string userURI) {
            PolarionPlug.ProjectApi.getUserAvatarURLRequest inValue = new PolarionPlug.ProjectApi.getUserAvatarURLRequest();
            inValue.userURI = userURI;
            PolarionPlug.ProjectApi.getUserAvatarURLResponse retVal = ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getUserAvatarURL(inValue);
            return retVal.getUserAvatarURLReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getUserAvatarURLResponse> PolarionPlug.ProjectApi.ProjectWebService.getUserAvatarURLAsync(PolarionPlug.ProjectApi.getUserAvatarURLRequest request) {
            return base.Channel.getUserAvatarURLAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getUserAvatarURLResponse> getUserAvatarURLAsync(string userURI) {
            PolarionPlug.ProjectApi.getUserAvatarURLRequest inValue = new PolarionPlug.ProjectApi.getUserAvatarURLRequest();
            inValue.userURI = userURI;
            return ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getUserAvatarURLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolarionPlug.ProjectApi.getUserByUriResponse PolarionPlug.ProjectApi.ProjectWebService.getUserByUri(PolarionPlug.ProjectApi.getUserByUriRequest request) {
            return base.Channel.getUserByUri(request);
        }
        
        public PolarionPlug.ProjectApi.User getUserByUri(string userURI) {
            PolarionPlug.ProjectApi.getUserByUriRequest inValue = new PolarionPlug.ProjectApi.getUserByUriRequest();
            inValue.userURI = userURI;
            PolarionPlug.ProjectApi.getUserByUriResponse retVal = ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getUserByUri(inValue);
            return retVal.getUserByUriReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getUserByUriResponse> PolarionPlug.ProjectApi.ProjectWebService.getUserByUriAsync(PolarionPlug.ProjectApi.getUserByUriRequest request) {
            return base.Channel.getUserByUriAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getUserByUriResponse> getUserByUriAsync(string userURI) {
            PolarionPlug.ProjectApi.getUserByUriRequest inValue = new PolarionPlug.ProjectApi.getUserByUriRequest();
            inValue.userURI = userURI;
            return ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getUserByUriAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolarionPlug.ProjectApi.getUsersResponse PolarionPlug.ProjectApi.ProjectWebService.getUsers(PolarionPlug.ProjectApi.getUsersRequest request) {
            return base.Channel.getUsers(request);
        }
        
        public PolarionPlug.ProjectApi.User[] getUsers() {
            PolarionPlug.ProjectApi.getUsersRequest inValue = new PolarionPlug.ProjectApi.getUsersRequest();
            PolarionPlug.ProjectApi.getUsersResponse retVal = ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getUsers(inValue);
            return retVal.getUsersReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getUsersResponse> PolarionPlug.ProjectApi.ProjectWebService.getUsersAsync(PolarionPlug.ProjectApi.getUsersRequest request) {
            return base.Channel.getUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionPlug.ProjectApi.getUsersResponse> getUsersAsync() {
            PolarionPlug.ProjectApi.getUsersRequest inValue = new PolarionPlug.ProjectApi.getUsersRequest();
            return ((PolarionPlug.ProjectApi.ProjectWebService)(this)).getUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PolarionPlug.ProjectApi.updateUserResponse PolarionPlug.ProjectApi.ProjectWebService.updateUser(PolarionPlug.ProjectApi.updateUserRequest request) {
            return base.Channel.updateUser(request);
        }
        
        public void updateUser(PolarionPlug.ProjectApi.User in0) {
            PolarionPlug.ProjectApi.updateUserRequest inValue = new PolarionPlug.ProjectApi.updateUserRequest();
            inValue.in0 = in0;
            PolarionPlug.ProjectApi.updateUserResponse retVal = ((PolarionPlug.ProjectApi.ProjectWebService)(this)).updateUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PolarionPlug.ProjectApi.updateUserResponse> PolarionPlug.ProjectApi.ProjectWebService.updateUserAsync(PolarionPlug.ProjectApi.updateUserRequest request) {
            return base.Channel.updateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<PolarionPlug.ProjectApi.updateUserResponse> updateUserAsync(PolarionPlug.ProjectApi.User in0) {
            PolarionPlug.ProjectApi.updateUserRequest inValue = new PolarionPlug.ProjectApi.updateUserRequest();
            inValue.in0 = in0;
            return ((PolarionPlug.ProjectApi.ProjectWebService)(this)).updateUserAsync(inValue);
        }
    }
}
